# Generated by Django 4.2 on 2023-05-05 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_alter_file_id_alter_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="favorite_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
