# Generated by Django 4.2 on 2023-04-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_file_content_alter_project_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="files",
        ),
        migrations.AddField(
            model_name="file",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="api.project",
            ),
            preserve_default=False,
        ),
    ]
